### ISSUE TITLE
md5 is BSD specific

### ISSUE THREAD

**Issue by cmungall** [cmungall/plmake#10]
The md5 tests run `md5` on the command line. This seems specific to BSD/OSX. Ubuntu has md5sum (not sure if args are the same). This causes the travis jobs to fail on 79.

Not sure if best option is to include a wrapper script and/or make the code test for availability of either and use the installed one, thoughts @ihh ?

**Comment by ihh** [comment]
hmmm
Guess we could try both, and fall back to `md5_hash` from the SWI-Prolog library, which is probably not as fast as the command-line utilities (and doesn't do streaming) but will be present everywhere:
http://www.swi-prolog.org/pldoc/doc/swi/library/md5.pl

**Comment by ihh** [comment]
out of interest, did travis automagically figure out that an output of "not ok" means that `make test` failed? I don't think it actually exits with an error code if it fails.

**Comment by ihh** [comment]
ah, ok, just saw #8 👍
